name: base
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  # - numpy
  # - pip
  # - pandas
  - matplotlib
  # - scikit-image=0.17.2
  # - scikit-learn=0.24.2
  - pytorch
  - torchvision
  - tensorflow
  # - opencv=3.4.1
  - opencv
  # - numpy=1.19.2
  - numpy
  # - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - pillow
  ###### Lorenz's Libs ######
  - pyproj
  - folium
  ###### extras ######
  - scikit-image
  - scikit-learn
  - tqdm
  - jupyterlab
  - nodejs
  - ipython
  - fastapi
  - joblib
  - flask
  - pip:
    - git+https://github.com/rjlopez2/toloboy.git
  #   # - tensorflow==2.1.0
  #   - tensorflow
    # - albumentations
  #     - cookiecutter
  #     - magicgui
  #     - napari[all]
  #     - sif_parser
  #     - twine
  #     - pytest
  #     - microfilm[all]
  #     - napari-svg
  #     - napari-omaas
  #     - napari-mat-file-reader
  #     - mat73 # this works
  #     - pymatreader
  # - anaconda:
  #     - git
